"""Fix share issuance model rebase

Revision ID: 37a820939be4
Revises: 56e3b5861ea9
Create Date: 2025-08-06 18:40:56.605767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37a820939be4'
down_revision: Union[str, Sequence[str], None] = '56e3b5861ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share_issuances', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_issuances', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
