"""Fix share issuance model and add audit events

Revision ID: 56e3b5861ea9
Revises: 9b82c26fbc61
Create Date: 2025-08-06 18:38:29.670830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56e3b5861ea9'
down_revision: Union[str, Sequence[str], None] = '9b82c26fbc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('share_issuances_ibfk_1'), 'share_issuances', type_='foreignkey')
    op.create_foreign_key(None, 'share_issuances', 'users', ['owner_id'], ['id'])
    op.drop_column('share_issuances', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_issuances', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'share_issuances', type_='foreignkey')
    op.create_foreign_key(op.f('share_issuances_ibfk_1'), 'share_issuances', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
