"""Add audit_event in user  table3

Revision ID: 9b82c26fbc61
Revises: aa68403e32b7
Create Date: 2025-08-06 18:26:52.126895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b82c26fbc61'
down_revision: Union[str, Sequence[str], None] = 'aa68403e32b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_issuances', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'share_issuances', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_issuances', type_='foreignkey')
    op.drop_column('share_issuances', 'owner_id')
    # ### end Alembic commands ###
