"""Add share certificates table

Revision ID: fffc9c2b36bb
Revises: 946f368f87b2
Create Date: 2025-08-04 17:20:58.234320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffc9c2b36bb'
down_revision: Union[str, Sequence[str], None] = '946f368f87b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuance_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issuance_id'], ['share_issuances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_certificates_id'), 'share_certificates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_certificates_id'), table_name='share_certificates')
    op.drop_table('share_certificates')
    # ### end Alembic commands ###
